### PR TITLE
Fix Icons and start refactor to script setup

### LINKED ISSUE #598: Dynamic import error in frontend
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/GoPlan-Finance/GoPlan-app/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/GoPlan-Finance/GoPlan-app/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/GoPlan-Finance/GoPlan-app/issues).
- [x] I can reproduce the issue with the [latest versions](https://github.com/GoPlan-Finance/GoPlan-app/releases). 

### Issue Description

In #489, it seems like we have an issue with dynamic imports:

image

### Steps to reproduce

Run Frontend

###  Environment

Server
- Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- FrontEnd version: `FILL_THIS_OUT`

### PR DESCRIPTION
**Pull request by mkitzmann**
Resolves #598

### CODE REVIEW

File: frontend/src/components/Header.vue [hunk 1]
```diff
@@ -2,62 +2,62 @@
...
+            class="relative z-10 block h-8 w-8 rounded-full overflow-hidden shadow focus:outline-none"
+            @click="dropdownOpen = !dropdownOpen"
         >
           <img
-            alt="Your avatar"
-            class="h-full w-full object-cover"
-            src="https://images.unsplash.com/photo-1528892952291-009c663ce843?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=296&q=80"
+              alt="Your avatar"
+              class="h-full w-full object-cover"
+              src="https://images.unsplash.com/photo-1528892952291-009c663ce843?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=296&q=80"
```
Comment (sadortun) [inline frontend/src/components/Header.vue:27]: I guess it's a placeholder for the profile picture ? Do you have a generic one with the icons library ? Or maybe use Gravatar?

**Review by sadortun — APPROVED** [review]

File: frontend/src/components/Header.vue (hunk 1 above)
Comment (mkitzmann) [reply frontend/src/components/Header.vue:27]: Actually I dont think we will have avatar pictures in the end, so maybe we should just show the user name in the header
